name: Checkout PyTorch

description: Clean workspace and check out PyTorch

inputs:
  no-sudo:
    description: If set to any value, don't use sudo to clean the workspace
    required: false

runs:
  using: composite
  steps:
    - name: Clean workspace
      shell: bash
      env:
        NO_SUDO: ${{ inputs.no-sudo }}
      run: |
        echo "${GITHUB_WORKSPACE}"
        if [ -z "${NO_SUDO}" ]; then
          sudo rm -rf "${GITHUB_WORKSPACE}"
        else
          rm -rf "${GITHUB_WORKSPACE}"
        fi
        mkdir "${GITHUB_WORKSPACE}"

    - name: echo
      shell: bash
      env:
        THING: ${{ toJSON(github.event) }}
      run: echo "$THING"
    - name: Checkout PyTorch
      uses: clee2000/checkout@fetch-depth
      with:
        ref: refs/heads/viable/strict
        fetch-depth: -1

    - name: Checkout PyTorch
      uses: clee2000/checkout@fetch-depth
      with:
        ref: refs/heads/master
        fetch-depth: -1

    - name: Checkout PyTorch
      uses: clee2000/checkout@fetch-depth
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        # deep clone, to allow use of git merge-base
        fetch-depth: ${{ github.event_name == 'pull_request' && github.event.pull_request.commits || github.event.commits.length || 100 }}
        submodules: recursive
